api/urls.py
from django.urls import path 
from . import views

app_name = "api"

urlpatterns = [
    path("", views.UserModelView.as_view(), name = "index"),
    path("<int:id>", views.UserModelView.as_view(), name = "delete"),
    path("sysinfo/ram", views.get_ram_usage),
    path("sysinfo/cpu", views.get_cpu_usage)
]

core/urls.py
from django.urls import path 
from . import views

app_name = "core"

urlpatterns = [
    path("", views.index, name = "index"),
    path("rules/", views.rulesView, name = "rules_view"),
    path("users/", views.users, name = "users"),
    path("users/<int:id>", views.user_profile, name = "user_profile"),
    path("dhcp/", views.dhcp_view, name = "dhcp_view"),
    path("filter/", views.filter, name = "filter_view")
    # path("sysinfo/ram", views.SysInfo.cpu_graph),
    # path("sysinfo/cpu", views.SysInfo.ram_graph),
    # path("sysinfo/storage", views.SysInfo.storage_graph),
]

dhcp/urls.py
from django.urls import path
from . import views

app_name = "dhcp"

urlpatterns = [
    path("", views.change_dhcp_form, name = "change_dhcp"),
    path("table", views.get_dhcp_table, name = "get_dhcp_table")
]

filter/urls.py
from django.urls import path

from . import views

app_name = "filter"

urlpatterns = [
    path("add/", views.add_filter, name = "add_filter"),
    path("edit/<int:ID>", views.edit_filter, name = "edit_filter"),
    path("delete/<int:ID>", views.delete_filter, name = "delete_filter")
]

dhcp/models.py
from django.db import models

# Create your models here.

class IPAddress(models.Model):
    address = models.GenericIPAddressField()
    hostname = models.CharField(max_length=255)

    def __str__(self):
        return self.address

filter/models.py
from django.db import models

class Filter(models.Model):

    CATEGORIES_CHOICES = {
        "Pornography": "Pornography",
        "Politics":"Politics",
        "Entertainment" : "Entertainment"
    }

    ACTION_CHOICES = {
        "Block":"Block",
        "Alert":"Alert",
        "Log":"Log",
        "Redirect":"Redirect",
        "Sanitize":"Sanitize"
    }

    category = models.CharField(max_length=50, choices = CATEGORIES_CHOICES)
    action = models.CharField(max_length=50, choices = ACTION_CHOICES, default = ACTION_CHOICES["Block"])
    domain = models.CharField(max_length=50)
    active = models.BooleanField(default = True)

    def __str__(self):
        return self.domain

core/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from dhcp.utils import *
from HomeWall.settings import LOGIN_URL
from accounts.models import User
from iptables.models import IptablesRule
from filter.models import Filter
from dhcp.display_ips import scan_network

@staff_member_required(login_url=LOGIN_URL)
def index(request):
    return render(request, "core/index.html")

@staff_member_required(login_url=LOGIN_URL)
def rulesView(request):
    rules = IptablesRule.objects.all()
    context = {"rules":rules}
    return render(request, "core/rules.html", context)

@staff_member_required(login_url=LOGIN_URL)
def users(request):
    users = User.objects.all()
    context = {"users":users}
    return render(request, "core/users.html", context)

@staff_member_required(login_url=LOGIN_URL)
def user_profile(request, id):
    return render(request, "core/users-profile.html")

@staff_member_required(login_url=LOGIN_URL)
def dhcp_view(request):
    values = parse_config("./dhcp/dnsmasq.conf")

    address = values["address"]
    start_ip = values["start_ip"]
    end_ip = values["end_ip"]
    mask = values["mask"]
    restart_time = values["restart_time"]

    #get ip table
    ips_arr = scan_network()

    context = {"address": address, "start":start_ip, 
    "end":end_ip, "dhcp_mask":mask, "restart_time": restart_time, "table":ips_arr}
    return render(request, "core/dhcp.html", context)

@staff_member_required(login_url=LOGIN_URL)
def filter(request):
    filters = Filter.objects.all()

    actions = Filter.ACTION_CHOICES
    categories = Filter.CATEGORIES_CHOICES

    context = {"filters":filters, "actions":actions, "categories":categories}
    return render(request, "core/filter.html", context)

dhcp/views.py
import json

from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse

from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

from HomeWall.settings import LOGIN_URL

from .display_ips import scan_network
from .utils import edit_dnsmasq_conf


@staff_member_required(login_url=LOGIN_URL)
def change_dhcp_form(request):
    if request.method == "POST":
        start_value = request.POST["dhcp-start"] # 1 It can't start with 0 because it was already taken by the address field in conf file
        ending_value = request.POST["dhcp-end"] #254
        address = request.POST["dhcp-address"] #  192.168.1 for instance
        mask = request.POST["dhcp-mask"]
        reset_time =  request.POST["dhcp-reset-time"]
        try:
            edit_dnsmasq_conf(f"{start_value}, {ending_value},{mask},{reset_time}", f"{address}", "./dhcp/dnsmasq.conf" )
        except FileNotFoundError:
            print("file was not found")
    return HttpResponseRedirect(reverse("core:dhcp_view"))

@staff_member_required(login_url=LOGIN_URL)
def get_dhcp_table(request):
    if request.method == "GET":
        table = scan_network()
        return JsonResponse(table, safe = False)
    return JsonResponse({"error":"POST/DELETE/PUT methods are not allowed."})

filter/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from .models import Filter

def add_filter(request):
    if request.method == "POST":
        domain = request.POST["domain"]
        action = request.POST["action"]
        category = request.POST["category"]

        f = Filter(category = category, action = action, domain = domain)
        f.save()

        return HttpResponseRedirect(reverse("core:filter_view"))

def edit_filter(request, ID):
    if request.method == "POST":
        filter = Filter.objects.get(id = ID)

        domain = request.POST["domain"]
        action = request.POST["action"]
        category = request.POST["category"]

        filter.domain = domain
        filter.action = action
        filter.category = category
        filter.save()

        return HttpResponseRedirect(reverse("core:filter_view"))

def delete_filter(request, ID):
    if request.method == "POST":
        filter = Filter.objects.get(id = ID)
        filter.delete()
        return HttpResponseRedirect(reverse("core:filter_view"))

    return HttpResponse("INCORRECT METHOD!")

core/templates/core/dhcp.html
{% extends "core/layout.html" %} {% load static %} {% block body %}

<main id="main" class="main">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">DHCP Server Configuration</h5>
            <div class="search-bar">
                <form
                    class="search-form d-flex align-items-center"
                    method="POST"
                    action="#"
                >
                    <input
                        type="text"
                        name="query"
                        placeholder="Search"
                        title="Enter search keyword"
                    />
                    <button type="submit" title="Search">
                        <i class="bi bi-search"></i>
                    </button>
                </form>
            </div>
            <form
                class="dhcp-configuration-form"
                method="POST"
                action="{% url 'dhcp:change_dhcp'%}"
            >
                {%csrf_token%}
                <div class="col">
                    <label for="dhcp-name">IP adress range (start value)</label>
                    <input
                        type="text"
                        class="form-control"
                        name="dhcp-start"
                        placeholder="IP starting value (e.g. 1)"
                        value = "{{start}}"
                        />
                </div><br>
                <div class="col">
                    <label for="dhcp-name"
                        >IP adress range (ending value)</label
                    >
                    <input
                        type="text"
                        class="form-control"
                        name="dhcp-end"
                        placeholder="IP ending value (e.g. 254)"
                        value = "{{end}}"
                    />
                </div><br>
                <div class="col">
                    <label for="dhcp-mask">Mask </label>
                    <input
                        type="text"
                        class="form-control"
                        name="dhcp-mask"
                        placeholder="Type in the Mask"
                        value = "{{dhcp_mask}}"
                        />
                </div><br>
                <div class="col">
                    <label for="dhcp-reset-time">Reset time</label>
                    <input
                        type="text"
                        class="form-control"
                        name="dhcp-reset-time"
                        placeholder="Type in the value (in hours)"
                        value = "{{restart_time}}"/>      
                </div><br>
                <div class="col">
                    <label for="dhcp-name">Address</label>
                    <input
                        type="text"
                        class="form-control"
                        name="dhcp-address"
                        placeholder="Address (e.g. 192.168.1.0)"
                        value = "{{address}}"
                    />
                </div><br>
                <button class="btn btn-primary">Submit</button>
            </form>
            <h5 class="card-title">DHCP TABLE</h5>
              <table class="table">
                <thead class="thead-light">
                  <tr>
                    <th scope="col">IP</th>
                    <th scope="col">MAC</th>
                    <th scope="col">Hostname</th>
                  </tr>
                </thead>
                <tbody id = "device-table-body">
                  {%for item in table%}
                  <tr>
                    <th scope="row">{{item.ip}}</th>
                    <td>{{item.mac}}</td>
                    <td>{{item.hostname}}</td>
                  </tr>
                  {%endfor%}
                </tbody>
              </table>     
    </div>
</main>

{% endblock body %} 
{% block scripts %}
<script src="{% static 'core/js/jquery.js' %}"></script>
<script src="{% static 'core/js/jquery.min.js' %}"></script>
<script src="{% static 'core/js/jquery-3.4.1.slim.min.js' %}"></script>
<script src="{% static 'core/js/jqueryformodals.slim.min.js' %}"></script>
<script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
></script>
<script
    src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
></script>
<script src = "{%static 'core/js/dhcp.js' %}"></script>
{% endblock scripts %}

core/templates/core/filter.html
{% extends "core/layout.html" %}
{% load static %}
{% block body %}

<main id="main" class="main">
  
  <div class="card">
    <div class="card-body">
      <h5 class="card-title">Content Filter</h5>
      <div class="search-bar">
        <form class="search-form d-flex align-items-center" method="POST" action="#">
          <input type="text" name="query" placeholder="Search" title="Enter search keyword">
          <button type="submit" title="Search"><i class="bi bi-search"></i></button>
        </form>
      </div>
      
      <!-- Dark Table -->
      <table class="table table-primary">
        <thead>
          <tr>
            
            <th scope="col">Domain</th>
            <th scope="col">Category</th>
            <th scope="col">Action</th>
            <th scope="col">Active</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
            {% for filter in filters %}
            <tr>
                <td>{{filter.domain}}</td>
                <td>{{filter.category}}</td>
                <td>{{filter.action}}</td>
                <td>{{filter.active}}</td>  
                <td><button type="button" class="btn btn-info" data-toggle="modal" data-target="#editFilter{{filter.id}}">
                  <i class = "bi bi-pencil"></i>
                </button></td>
                <td><form action="{% url "filter:delete_filter" filter.id %} " method = "post">
                  {% csrf_token %}
                  <button type = "submit" class = "btn btn-danger">
                  <i class = "bi bi-trash"></i>
                </button></form></td>
              </tr>
              <!--Modal window for editing filter-->
          <div class="modal fade" id="editFilter{{filter.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="editFilter{{filter.id}}Label">Edit Filter</h5>
                  <button type="button" class="btn btn-light close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class = "bi bi-x-lg"></i></span>
                  </button>
                </div>
                <div class="modal-body">
                  <form action="{% url "filter:edit_filter" filter.id %}" method = "post">
                    {% csrf_token %}
                    <label for="domain">Domain: </label>
                    <input type="text" class = "form-control" value = "{{filter}}" name="domain" placeholder="johndoe.com or *.com"><br>

                    <label for="action">Action: </label>
                    <select class="form-select" name = "action" aria-label="select example">
                        {% for action in actions %}
                          {% if action == filter.action %}
                            <option value = "{{action}}" selected>{{action}}</option>
                          {% else %}
                            <option value = "{{action}}">{{action}}</option>
                          {% endif %}
                        {% endfor %}
                    
                    </select> <br>

                    <label for="category">Categories: </label>
                    <select class="form-select" name="category" aria-label="select example">
                        {% for category in categories %}
                          {% if category == filter.category %}
                          <option value="{{category}}" selected>{{category}}</option>
                          {% else %}
                          <option value="{{category}}">{{category}}</option>
                          {% endif %}
                        {% endfor %}
                    </select><br>
                  
                    <button type="submit" class="btn btn-primary">Save changes</button>
                  </form>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
            {% endfor %}
          
          
        </tbody>
      </table>
      <!-- End Dark Table -->
      <!-- Button trigger modal -->
<button type="button" class="btn btn-success" data-toggle="modal" data-target="#addFilter">
  Add Rule
</button>

            <!-- Modal for adding filter -->
          <div class="modal fade" id="addFilter" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="addFilterLabel">Add Filter</h5>
                  <button type="button" class="btn btn-light close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true"><i class = "bi bi-x-lg"></i></span>
                  </button>
                </div>
                <div class="modal-body">
                  
                    <form action="{% url "filter:add_filter" %}" method = "post">
                        {% csrf_token %}
                        <label for="domain">Domain: </label>
                        <input type="text" class = "form-control" name="domain" placeholder="johndoe.com or *.com"><br>
    
                        <label for="action">Action: </label>
                        <select class="form-select" name = "action" aria-label="select example">
                            {% for action in actions %}
                            <option value = "{{action}}" selected>{{action}}</option>
                            {% endfor %}
                        
                        </select> <br>

                        <label for="category">Categories: </label>
                        <select class="form-select" name="category" aria-label="select example">
                            {% for category in categories %}
                                <option value="{{category}}">{{category}}</option>
                            {% endfor %}
                        </select><br>
                      
                        <button type="submit" class="btn btn-success">Add</button>
                      </form>
                  
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>

          
    </div>
  </div>




</main>


{% endblock body %}

{% block scripts %}
<script src = "{% static "core/js/jquery.js" %}"></script>
<script src = "{% static "core/js/jquery.min.js" %}"></script>
<script src = "{% static "core/js/jquery-3.4.1.slim.min.js" %}"></script>
<script src = "{% static 'core/js/jqueryformodals.slim.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% endblock scripts %}